name: "Deploy a Deco Site"
description: "Deploy any deco site to deco infrastructure"
branding:
  icon: "arrow-right-circle"
  color: "gray-dark"
inputs:
  entrypoint:
    description: "The application entrypoint, defaults to main.ts"
    required: false
    default: "./main.ts"
  site:
    description: "The site name"
    required: false
    default: ${{ github.event.repository.name }}
  skip_build:
    description: "If build should be skipped"
    required: false
    default: "false"
  build_cmd:
    description: "The build cmd that should be used."
    required: false
    default: "deno run -A dev.ts build"
  exclude:
    description: "Folders/files to exclude for deploying"
    required: false
    default: "node_modules"
runs:
  using: "composite"
  steps:
    - name: Clone repository
      uses: actions/checkout@v3

    - name: Install Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x

    - name: Build step
      shell: bash
      if: ${{ inputs.skip_build == 'false' }}
      run: ${{ inputs.build_cmd }}

    - name: Clean unnecessary files # this is only necessary because deployctl does not have an option to exclude directories https://github.com/denoland/deployctl/issues/181
      shell: bash
      run: |
        rm -rf node_modules
        rm -rf .git
        rm -rf .gitattributes
        rm -rf CHANGELOG.md
        rm -rf README.md
        rm -rf .vscode

    - name: Upload to Deno Deploy
      uses: denoland/deployctl@v1
      with:
        project: "deco-sites-${{ inputs.site }}"
        entrypoint: ${{ inputs.entrypoint }}
        exclude: ${{ inputs.exclude }}
