name: "Deploy a Deco Site"
description: "Deploy any deco site to deco infrastructure"
branding:
  icon: "arrow-right-circle"
  color: "gray-dark"
inputs:
  entrypoint:
    description: "The application entrypoint, defaults to main.ts"
    required: false
    default: "./main.ts"
  build_cmd:
    description: "The build cmd that should be used."
    required: false
    default: "deno run -A dev.ts build"
runs:
  using: "composite"
  steps:
    - name: Clone repository
      uses: actions/checkout@v3

    - name: Install Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x

    - name: Build step
      shell: bash
      run: ${{ inputs.build_cmd }} # 📝 Update the build command(s) if necessary

    - name: Upload to Deno Deploy
      uses: denoland/deployctl@v1
      with:
        project: "deco-sites-${{ github.event.repository.name }}" # 📝 Update the deploy project name if necessary
        entrypoint: ${{ inputs.entrypoint }} # 📝 Update the entrypoint if necessary
